### PR TITLE
Create gb-rules.yml

### PR DESCRIPTION
**Pull request by golfvert**
To be saved as rules.yml. It pre-calculates a "combined" metric.

### CODE REVIEW

**Comment by kaiwirt** [comment]
Is there a reason why this needs to be in a different file? Can this be moved to gb.yml?
Should we rename this to rules.yml and maybe add precomputations for the other services here as well?

**Comment by golfvert** [comment]
On that same repo we have, at the moment, three different elements:
- the metrics in gb.csv (gc.csv...)
- the alerts, what to do if something is wrong. This will end up in alert.yml file in prometheus
- potentially rules (to compute secondary metrics based on the origin ones). Typically, this goes in rules.yml.

I just wanted to show that...

**Comment by kaiwirt** [comment]
My point is you can have each of them in their own file. So maybe gb-alerts.yml, gb-rules.yml, gc-alert.yml, gc-rules.yml?

Or better create two big files from the single parts alerts.yml and rules.yml as you suggested?

**Comment by golfvert** [comment]
No real preference for me...
We could eg at the top level create a directory for the metrics, then we put gb.yml, gc.yml in there.
Another directory for rules and alerts (correcponding to what prometheus will do)
A potential last one for alertmanager and the agreed configuration group_internal, repeat...
We just need a bit of structure. Whatever it is :)

**Pull request merged**
