### PR TITLE
define alert rule for missing GDC metadata archive (#13)

### LINKED ISSUE #13: define alert rule for missing GDC metadata archive
In cases where a GDC does not produce a metadata archive zipfile on a daily basis (noting the 24 hour retention time for GC), there exists a risk / gap in not being able to cold start a GDC from a known archive.  Consider raising an alert in this case.

### PR DESCRIPTION
**Pull request by tomkralidis**
Fixes #13.  Also moves commented lines to annotations.

### CODE REVIEW

**Comment by kaiwirt** [comment]
Following the discussion on #13 the alert rule still needs to be updated such that it filters only by GDCs. Otherwise it would trigger an alert for all centers not updating their metadata in 24 hours.

**Comment by tomkralidis** [comment]
> Following the discussion on #13 the alert rule still needs to be updated such that it filters only by GDCs. Otherwise it would trigger an alert for all centers not updating their metadata in 24 hours.

I can see that `centre_id =~ ".*global-discovery-catalogue"` then needs to be part of the alert definition.  Is the below correct?

`time() - wmo_wis2_gc_last_metadata_timestamp_seconds{centre_id =~ ".*global-discovery-catalogue"} > 86400`

Once I have a validation I will update this PR accordingly.

**Comment by kaiwirt** [comment]
The syntax seems to be correct. As #13 is not yet implemented by Global Caches for the GDC archive at the moment this alert would fire

**Comment by tomkralidis** [comment]
> The syntax seems to be correct. As #13 is not yet implemented by Global Caches for the GDC archive at the moment this alert would fire

PR updated accordingly for review.

**Pull request merged**
